### ISSUE TITLE
HTTPS_PROXY ENV Var is not used

### ISSUE THREAD

**Issue by dja** [launchdarkly/ruby-server-sdk#182]
The documentation states to use `HTTPS_PROXY` as well as `HTTP_PROXY` but this line is not picking up the first env var.

https://github.com/launchdarkly/ruby-server-sdk/blob/aa219b5ec60d979b74ab6c8a710324b2d038bea0/lib/ldclient-rb/impl/diagnostic_events.rb#L82

**Comment by bwoskow-ld** [comment]
Hi @dja,

You're correct that the line of code you referenced does not handle `HTTPS_PROXY`. However, this code is only used for the generation of diagnostic events sent by the SDK to LaunchDarkly's servers. This code isn't used for setting connection properties and has no impact on any customer-visible SDK functionality.

We can certainly fix this issue, but I wanted to verify that this is in line with what you're seeing, as opposed to you thinking that this line is related to possible connection issues that you may be encountering.

Cheers,
@bwoskow-ld

**Comment by bwoskow-ld** [comment]
Hi @dja,

The issue you reported is fixed in SDK [version 6.2.3](https://github.com/launchdarkly/ruby-server-sdk/releases/tag/6.2.3). 

I'll leave this ticket open for a few more days for you to respond to my earlier response around if you were seeing anything else relating to proxy configuration when reporting this issue.

Cheers,
@bwoskow-ld
